require "freeranger.remap"
require "freeranger.set"
require "freeranger.plugins"

require "freeranger.neovide"

require "freeranger.after.telescope"
require "freeranger.after.catppuccin"
require "freeranger.after.treesitter"
require "freeranger.after.undotree"
require "freeranger.after.lualine"
require "freeranger.after.lsp"
require "freeranger.after.whichkey"
require "freeranger.after.autopairs"
require "freeranger.after.comment"
require "freeranger.after.toggleterm"
require "freeranger.after.alpha"
